---
development:
  cloud_name: dfg9corup
  api_key: '574396291143426'
  api_secret: 0p1d2QlSbRDokVJYbqtiio2N0NM
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dfg9corup
  api_key: '574396291143426'
  api_secret: 0p1d2QlSbRDokVJYbqtiio2N0NM
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dfg9corup
  api_key: '574396291143426'
  api_secret: 0p1d2QlSbRDokVJYbqtiio2N0NM
  enhance_image_tag: true
  static_image_support: false
